// MIT License
//
// Copyright (c) 2017-present qazyn951230 qazyn951230@gmail.com
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#ifndef REFLECTION_CRDNODEKIND_H
#define REFLECTION_CRDNODEKIND_H

#include "Config.h"

#if (__cplusplus)
#include <cstdint>
#else
#include <stdint.h>
#endif // (__cplusplus)

SP_C_FILE_BEGIN

typedef SP_ENUM(uint16_t, CRDNodeKind) {
    CRDNodeKindAllocator,
    CRDNodeKindAnonymousContext,
    CRDNodeKindAnyProtocolConformanceList,
    CRDNodeKindArgumentTuple,
    CRDNodeKindAssociatedType,
    CRDNodeKindAssociatedTypeRef,
    CRDNodeKindAssociatedTypeMetadataAccessor,
    CRDNodeKindDefaultAssociatedTypeMetadataAccessor,
    CRDNodeKindAssociatedTypeWitnessTableAccessor,
    CRDNodeKindBaseWitnessTableAccessor,
    CRDNodeKindAutoClosureType,
    CRDNodeKindBoundGenericClass,
    CRDNodeKindBoundGenericEnum,
    CRDNodeKindBoundGenericStructure,
    CRDNodeKindBoundGenericProtocol,
    CRDNodeKindBoundGenericOtherNominalType,
    CRDNodeKindBoundGenericTypeAlias,
    CRDNodeKindBoundGenericFunction,
    CRDNodeKindBuiltinTypeName,
    CRDNodeKindCFunctionPointer,
    CRDNodeKindClass,
    CRDNodeKindClassMetadataBaseOffset,
    CRDNodeKindConcreteProtocolConformance,
    CRDNodeKindConstructor,
    CRDNodeKindCoroutineContinuationPrototype,
    CRDNodeKindDeallocator,
    CRDNodeKindDeclContext,
    CRDNodeKindDefaultArgumentInitializer,
    CRDNodeKindDependentAssociatedConformance,
    CRDNodeKindDependentAssociatedTypeRef,
    CRDNodeKindDependentGenericConformanceRequirement,
    CRDNodeKindDependentGenericParamCount,
    CRDNodeKindDependentGenericParamType,
    CRDNodeKindDependentGenericSameTypeRequirement,
    CRDNodeKindDependentGenericLayoutRequirement,
    CRDNodeKindDependentGenericSignature,
    CRDNodeKindDependentGenericType,
    CRDNodeKindDependentMemberType,
    CRDNodeKindDependentPseudogenericSignature,
    CRDNodeKindDependentProtocolConformanceRoot,
    CRDNodeKindDependentProtocolConformanceInherited,
    CRDNodeKindDependentProtocolConformanceAssociated,
    CRDNodeKindDestructor,
    CRDNodeKindDidSet,
    CRDNodeKindDirectness,
    CRDNodeKindDynamicAttribute,
    CRDNodeKindDirectMethodReferenceAttribute,
    CRDNodeKindDynamicSelf,
    CRDNodeKindDynamicallyReplaceableFunctionImpl,
    CRDNodeKindDynamicallyReplaceableFunctionKey,
    CRDNodeKindDynamicallyReplaceableFunctionVar,
    CRDNodeKindEnum,
    CRDNodeKindEnumCase,
    CRDNodeKindErrorType,
    CRDNodeKindEscapingAutoClosureType,
    CRDNodeKindNoEscapeFunctionType,
    CRDNodeKindExistentialMetatype,
    CRDNodeKindExplicitClosure,
    CRDNodeKindExtension,
    CRDNodeKindFieldOffset,
    CRDNodeKindFullTypeMetadata,
    CRDNodeKindFunction,
    CRDNodeKindFunctionSignatureSpecialization,
    CRDNodeKindFunctionSignatureSpecializationParam,
    CRDNodeKindFunctionSignatureSpecializationReturn,
    CRDNodeKindFunctionSignatureSpecializationParamKind,
    CRDNodeKindFunctionSignatureSpecializationParamPayload,
    CRDNodeKindFunctionType,
    CRDNodeKindGenericPartialSpecialization,
    CRDNodeKindGenericPartialSpecializationNotReAbstracted,
    CRDNodeKindGenericProtocolWitnessTable,
    CRDNodeKindGenericProtocolWitnessTableInstantiationFunction,
    CRDNodeKindResilientProtocolWitnessTable,
    CRDNodeKindGenericSpecialization,
    CRDNodeKindGenericSpecializationNotReAbstracted,
    CRDNodeKindGenericSpecializationParam,
    CRDNodeKindInlinedGenericFunction,
    CRDNodeKindGenericTypeMetadataPattern,
    CRDNodeKindGetter,
    CRDNodeKindGlobal,
    CRDNodeKindGlobalGetter,
    CRDNodeKindIdentifier,
    CRDNodeKindIndex,
    CRDNodeKindIVarInitializer,
    CRDNodeKindIVarDestroyer,
    CRDNodeKindImplEscaping,
    CRDNodeKindImplConvention,
    CRDNodeKindImplFunctionAttribute,
    CRDNodeKindImplFunctionType,
    CRDNodeKindImplicitClosure,
    CRDNodeKindImplParameter,
    CRDNodeKindImplResult,
    CRDNodeKindImplErrorResult,
    CRDNodeKindInOut,
    CRDNodeKindInfixOperator,
    CRDNodeKindInitializer,
    CRDNodeKindKeyPathGetterThunkHelper,
    CRDNodeKindKeyPathSetterThunkHelper,
    CRDNodeKindKeyPathEqualsThunkHelper,
    CRDNodeKindKeyPathHashThunkHelper,
    CRDNodeKindLazyProtocolWitnessTableAccessor,
    CRDNodeKindLazyProtocolWitnessTableCacheVariable,
    CRDNodeKindLocalDeclName,
    CRDNodeKindMaterializeForSet,
    CRDNodeKindMergedFunction,
    CRDNodeKindMetatype,
    CRDNodeKindMetatypeRepresentation,
    CRDNodeKindMetaclass,
    CRDNodeKindMethodLookupFunction,
    CRDNodeKindObjCMetadataUpdateFunction,
    CRDNodeKindObjCResilientClassStub,
    CRDNodeKindFullObjCResilientClassStub,
    CRDNodeKindModifyAccessor,
    CRDNodeKindModule,
    CRDNodeKindNativeOwningAddressor,
    CRDNodeKindNativeOwningMutableAddressor,
    CRDNodeKindNativePinningAddressor,
    CRDNodeKindNativePinningMutableAddressor,
    CRDNodeKindNominalTypeDescriptor,
    CRDNodeKindNonObjCAttribute,
    CRDNodeKindNumber,
    CRDNodeKindObjCAttribute,
    CRDNodeKindObjCBlock,
    CRDNodeKindEscapingObjCBlock,
    CRDNodeKindOtherNominalType,
    CRDNodeKindOwningAddressor,
    CRDNodeKindOwningMutableAddressor,
    CRDNodeKindPartialApplyForwarder,
    CRDNodeKindPartialApplyObjCForwarder,
    CRDNodeKindPostfixOperator,
    CRDNodeKindPrefixOperator,
    CRDNodeKindPrivateDeclName,
    CRDNodeKindPropertyDescriptor,
    CRDNodeKindPropertyWrapperBackingInitializer,
    CRDNodeKindProtocol,
    CRDNodeKindProtocolSymbolicReference,
    CRDNodeKindProtocolConformance,
    CRDNodeKindProtocolConformanceRefInTypeModule,
    CRDNodeKindProtocolConformanceRefInProtocolModule,
    CRDNodeKindProtocolConformanceRefInOtherModule,
    CRDNodeKindProtocolDescriptor,
    CRDNodeKindProtocolConformanceDescriptor,
    CRDNodeKindProtocolList,
    CRDNodeKindProtocolListWithClass,
    CRDNodeKindProtocolListWithAnyObject,
    CRDNodeKindProtocolSelfConformanceDescriptor,
    CRDNodeKindProtocolSelfConformanceWitness,
    CRDNodeKindProtocolSelfConformanceWitnessTable,
    CRDNodeKindProtocolWitness,
    CRDNodeKindProtocolWitnessTable,
    CRDNodeKindProtocolWitnessTableAccessor,
    CRDNodeKindProtocolWitnessTablePattern,
    CRDNodeKindReabstractionThunk,
    CRDNodeKindReabstractionThunkHelper,
    CRDNodeKindReabstractionThunkHelperWithSelf,
    CRDNodeKindReadAccessor,
    CRDNodeKindRelatedEntityDeclName,
    CRDNodeKindRetroactiveConformance,
    CRDNodeKindReturnType,
    CRDNodeKindShared,
    CRDNodeKindOwned,
    CRDNodeKindSILBoxType,
    CRDNodeKindSILBoxTypeWithLayout,
    CRDNodeKindSILBoxLayout,
    CRDNodeKindSILBoxMutableField,
    CRDNodeKindSILBoxImmutableField,
    CRDNodeKindSetter,
    CRDNodeKindSpecializationPassID,
    CRDNodeKindIsSerialized,
    CRDNodeKindStatic,
    CRDNodeKindStructure,
    CRDNodeKindSubscript,
    CRDNodeKindSuffix,
    CRDNodeKindThinFunctionType,
    CRDNodeKindTuple,
    CRDNodeKindTupleElement,
    CRDNodeKindTupleElementName,
    CRDNodeKindType,
    CRDNodeKindTypeSymbolicReference,
    CRDNodeKindTypeAlias,
    CRDNodeKindTypeList,
    CRDNodeKindTypeMangling,
    CRDNodeKindTypeMetadata,
    CRDNodeKindTypeMetadataAccessFunction,
    CRDNodeKindTypeMetadataCompletionFunction,
    CRDNodeKindTypeMetadataInstantiationCache,
    CRDNodeKindTypeMetadataInstantiationFunction,
    CRDNodeKindTypeMetadataSingletonInitializationCache,
    CRDNodeKindTypeMetadataDemanglingCache,
    CRDNodeKindTypeMetadataLazyCache,
    CRDNodeKindUncurriedFunctionType,
    CRDNodeKindUnknownIndex,

// "swift/AST/ReferenceStorage.def"
    CRDNodeKindWeak,
    CRDNodeKindUnowned,
    CRDNodeKindUnmanaged,
// "swift/AST/ReferenceStorage.def"

    CRDNodeKindUnsafeAddressor,
    CRDNodeKindUnsafeMutableAddressor,
    CRDNodeKindValueWitness,
    CRDNodeKindValueWitnessTable,
    CRDNodeKindVariable,
    CRDNodeKindVTableThunk,
    CRDNodeKindVTableAttribute, // note: old mangling only
    CRDNodeKindWillSet,
    CRDNodeKindReflectionMetadataBuiltinDescriptor,
    CRDNodeKindReflectionMetadataFieldDescriptor,
    CRDNodeKindReflectionMetadataAssocTypeDescriptor,
    CRDNodeKindReflectionMetadataSuperclassDescriptor,
    CRDNodeKindGenericTypeParamDecl,
    CRDNodeKindCurryThunk,
    CRDNodeKindDispatchThunk,
    CRDNodeKindMethodDescriptor,
    CRDNodeKindProtocolRequirementsBaseDescriptor,
    CRDNodeKindAssociatedConformanceDescriptor,
    CRDNodeKindDefaultAssociatedConformanceAccessor,
    CRDNodeKindBaseConformanceDescriptor,
    CRDNodeKindAssociatedTypeDescriptor,
    CRDNodeKindThrowsAnnotation,
    CRDNodeKindEmptyList,
    CRDNodeKindFirstElementMarker,
    CRDNodeKindVariadicMarker,
    CRDNodeKindOutlinedBridgedMethod,
    CRDNodeKindOutlinedCopy,
    CRDNodeKindOutlinedConsume,
    CRDNodeKindOutlinedRetain,
    CRDNodeKindOutlinedRelease,
    CRDNodeKindOutlinedInitializeWithTake,
    CRDNodeKindOutlinedInitializeWithCopy,
    CRDNodeKindOutlinedAssignWithTake,
    CRDNodeKindOutlinedAssignWithCopy,
    CRDNodeKindOutlinedDestroy,
    CRDNodeKindOutlinedVariable,
    CRDNodeKindAssocTypePath,
    CRDNodeKindLabelList,
    CRDNodeKindModuleDescriptor,
    CRDNodeKindExtensionDescriptor,
    CRDNodeKindAnonymousDescriptor,
    CRDNodeKindAssociatedTypeGenericParamRef,
    CRDNodeKindSugaredOptional,
    CRDNodeKindSugaredArray,
    CRDNodeKindSugaredDictionary,
    CRDNodeKindSugaredParen,

    // Added in Swift 5.1
    CRDNodeKindAccessorFunctionReference,
    CRDNodeKindOpaqueType,
    CRDNodeKindOpaqueTypeDescriptorSymbolicReference,
    CRDNodeKindOpaqueTypeDescriptor,
    CRDNodeKindOpaqueTypeDescriptorAccessor,
    CRDNodeKindOpaqueTypeDescriptorAccessorImpl,
    CRDNodeKindOpaqueTypeDescriptorAccessorKey,
    CRDNodeKindOpaqueTypeDescriptorAccessorVar,
    CRDNodeKindOpaqueReturnType,
    CRDNodeKindOpaqueReturnTypeOf,
};

SP_C_FILE_END

#endif //REFLECTION_CRDNODEKIND_H
